# Generated by Django 2.1.7 on 2019-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mondaystart', models.IntegerField(default=0, null=True)),
                ('mondayend', models.IntegerField(default=0, null=True)),
                ('tuesdaystart', models.IntegerField(default=0, null=True)),
                ('tuesdayend', models.IntegerField(default=0, null=True)),
                ('wednesdaystart', models.IntegerField(default=0, null=True)),
                ('wednesdayend', models.IntegerField(default=0, null=True)),
                ('thursdaystart', models.IntegerField(default=0, null=True)),
                ('thursdayend', models.IntegerField(default=0, null=True)),
                ('fridaystart', models.IntegerField(default=0, null=True)),
                ('fridayend', models.IntegerField(default=0, null=True)),
                ('saturdaystart', models.IntegerField(default=0, null=True)),
                ('saturdayend', models.IntegerField(default=0, null=True)),
                ('sundaystart', models.IntegerField(default=0, null=True)),
                ('sundayend', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
